spring:
  main:
    banner-mode: "off"
  application:
    name: ahub-bot-telegram
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    initialization-mode: always
    hikari:
      schema: demoapp
      maximum-pool-size: 5
      connection-timeout: 60000
  liquibase:
    parameters:
      schema: demoapp
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.json
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: false
    hibernate:
      ddl-auto: none
